### ISSUE TITLE
SQLite: Expected integer, got something else

### ISSUE THREAD

**Issue by richb-hanover** [duckdblabs/sqlite_scanner#15]
Using duckdb 0.5.1 on macOS 12.6.1 (Monterey), I attempt to select an INTEGER column from a SQLite database and get `Error: Invalid Error: Expected integer, got something else`

Details:

* Download the macOS installer from https://duckdb.org/docs/installation/ and unzip it
* Copy the resulting binary to my test directory
* Download a copy of the [chinook SQLite database](https://github.com/lerocha/chinook-database/blob/master/ChinookDatabase/DataSources/Chinook_Sqlite.sqlite) to the same directory
* Start the program with `./duckdb`, then install/load sqlite_scanner (I don't know where these come from, nor their version) and open the SQLite database

Result: TEXT field works as expected; INTEGER field gives "Expected integer, got something else"

Here is the CLI session:

```
?137 pqtest % ./duckdb
v0.5.1 7c111322d
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D INSTALL sqlite_scanner;
D LOAD sqlite_scanner;
D CALL sqlite_attach('chinook.sqlite');
D select * from albums limit 5;
Error: Invalid Error: Expected integer, got something else
D select title from albums limit 5;
┌───────────────────────────────────────┐
│                 title                 │
├───────────────────────────────────────┤
│ title                                 │
│ For Those About To Rock We Salute You │
│ Balls to the Wall                     │
│ Restless and Wild                     │
│ Let There Be Rock                     │
└───────────────────────────────────────┘
D select album_id from albums limit 5;
Error: Invalid Error: Expected integer, got something else
```

**Comment by richb-hanover** [comment]
Here's the copy of the "chinook" database that I have been using. (I don't exactly remember where I got it...) I will note that this works fine with `sqlite3` on my Mac: 

```
SQLite 3.37.0 2021-12-09 01:34:53 9ff244ce0739f8ee52a3e9671adb4ee54c83c640b02e3f9d185fd2f9a179aapl
clang-13.1.6
```
[chinook.sqlite.zip](https://github.com/duckdblabs/sqlite_scanner/files/9944411/chinook.sqlite.zip)

**Comment by richb-hanover** [comment]
Summary: duckdb with sqlite_scanner works as expected for the canonical "Github chinook" database linked in the original post. It also works with the version from SQLite Tutorials. (You have to change the table name, but it handles integer columns as expected.)

What is surprising is that sqlite3 can handle integer columns from the chinook.sqlite.zip file (in the previous message), but sqlite_scanner cannot. 

How can we learn "what's wrong" with the chinook.sqlite.zip file? (In fact, I don't care about that particular file. But I have a SQLite database created by importing a bunch of CSV files using`sqlite3` that ALSO demonstrates the "Expected integer..." error.)

What's the best way to proceed? And where is the best place to continue this conversation: here? or on Discord? Many thanks.

**Comment by Mytherin** [comment]
Thanks for the report!

The linked chinook database appears to have a string value in an integer column. Opening the file in SQLite gives the following result:

```sql
sqlite> select min(album_id), max(album_id) from albums;;
min(album_id)  max(album_id)
-------------  -------------
1              album_id     
```

The text string "album_id" is included. This is likely caused by a CSV file being parsed into the database and including the header column.

The reason this works in SQLite is that SQLite does not have column types. All columns are implicitly of the "ANY" type, meaning that even though "album_id" is declared as an integer type, it can also contain string values. See [here for more information](https://www.sqlite.org/datatype3.html).

DuckDB explicitly does not support this - and this file is a great example of why DuckDB does not support this. The inclusion of the "album_id" value is almost certainly a mistake that would have been caught earlier if strict typing was enabled.

As such the error message thrown is correct and expected. We should definitely clarify the error message further by including the value and a more informative description, and add an option to the SQLite scanner to allow converting of all columns to `VARCHAR` (which will always succeed).

**Comment by richb-hanover** [comment]
Ahah! I think you have explained everything. The next question is, "What to do about it?"

1. A better error message would have helped enormously. Perhaps, "Expected integer, but got something else, ("album_id")" would have been a big tip-off. And given that duckdb aborts on the error, that message can be fairly expansive. Maybe even, "... got something else (text string "album_id")"
2. A paragraph in the duckdb documentation would also be useful, so that people looking up that message would get a hint.
3. Your diagnosis is right - I certainly have imported the column name into my numeric fields in my own DB. The reason that it didn't bite me already is that I did selects on other column contents that missed out the bad data.
4. You're also right - the behavior is correct - throwing the error. (Unfortunately for me, who now realizes I have dirty data)
5. An option to convert SQLite columns to VARCHAR could be useful. 

Thanks to all who worked on this.

**Comment by Mytherin** [comment]
Thanks for the report! This should be fixed by #18 now.

**Comment by richb-hanover** [comment]
@Mytherin Where can I find a link to the updated sqlite_scanner? I can only find a link to the 0.5.1 release... (I'm specifically looking for the macOS version (I got 0.5.1 from https://github.com/duckdb/duckdb/releases/download/v0.5.1/duckdb_cli-osx-universal.zip) Many thanks.

**Comment by Mytherin** [comment]
We are releasing a new version of DuckDB that will ship with the new SQLite scanner on Monday.

**Comment by richb-hanover** [comment]
Perfect. Thanks.

**Comment by richb-hanover** [comment]
**Update:**  @Mytherin 

1. I installed duckdb 0.6.0 as described in the initial issue, and can confirm that the error message provides much better diagnostic information. Thank you.

   ```
   D select * from albums limit 5;
   Error: Invalid Error: Mismatch Type Error: Invalid type in column "album_id": column was declared as integer, found "album_id" of type "text" instead.
   ```

2. The error message seems wordy to me. I might be tempted to rephrase as:

   `Error: Type Mismatch: Column "album_id": was declared as integer, found data of "album_id" (type "text")`

   I can't say for sure whether this text will handle all the combinations of screwups that I might generate :-)

Thank you again.
