### ISSUE TITLE
Inverse operation for CALL sqlite_attach(db_name)

### ISSUE THREAD

**Issue by smartexpert** [duckdblabs/sqlite_scanner#19]
There doesn't appear to be any documented way to detach a SQLite database from DuckDB CLI that was attached using `CALL sqlite_attach(db_name)`

**Comment by hannes** [comment]
There is indeed none at the moment

**Comment by Mytherin** [comment]
The new `ATTACH` syntax has a corresponding `DETACH`. We won't implement an inverse for `sqlite_attach` as it is mostly kept around for backwards compatibility reasons at this point.
