### ISSUE TITLE
duckdb coredumps when attaching a database that is not found

### ISSUE THREAD

**Issue by ededovic** [duckdblabs/sqlite_scanner#22]
### What happens?

seg fault while attempting to attach any database that does not exist. 
Linux version: `Linux ... 3.10.0-1127.13.1.el7.x86_64 #1 SMP Tue Jun 23 15:46:38 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

using strace the issue appears that it can not find the example database decimal.db. After downloading the database, it does not produce segfalt. This should be an easy fix I suppose. Workaround is to ensure that one has the database in the path. 

`lstat("decimal.db", 0x7ffe5d42f830)     = -1 ENOENT (No such file or directory)
getcwd("misc", 511) = 29
open("misc/decimal.db", O_RDONLY|O_NOFOLLOW|O_CLOEXEC) = -1 ENOENT (No such file or directory)
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x73} ---
+++ killed by SIGSEGV (core dumped) +++
Segmentation fault (core dumped)
`

### To Reproduce

Complete script: 

```py
import duckdb
duck = duckdb.connect()
duck.execute("load sqlite;").fetchall()
duck.execute("CALL sqlite_attach('does_not_exist.db');")
```

Results in 

`Segmentation fault (core dumped)`

### OS:

Linux 3.10.0-1127.13.1.el7.x86_64 #1 SMP Tue Jun 23 15:46:38 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### SQLite Version:

3.39.2 and 3.39.3

### DuckDB Version:

0.6.0 and 0.6.1-dev86

### DuckDB Client:

python

### Full Name:

e d

### Affiliation:

can not disclose

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hannes** [comment]
Thanks for the report, can you maybe say why you can't disclose your affiliation? Email to hannes@duckblabs.com is also possible.

**Comment by Mytherin** [comment]
This seems to work correctly for me in v0.6.1. Feel free to re-open if the issue persists.
