### ISSUE TITLE
how can I check the version of sqlite scanner extension used or how to get the latest version of sqlite scanner?

### ISSUE THREAD

**Issue by ededovic** [duckdblabs/sqlite_scanner#23]
After running `install sqlite`, how can one check the version of sqlite scanner or is it always linked to duckdb release. For example, there was a bug reported with `select count(*) from table` producing a segfaults, and I can see that it was maybe fixed, but unclear how to take that latest version of sqlite scanner. Is it sufficient to do this `pip install duckdb --upgrade --pre` and then run `install sqlite` again?

**Comment by Mause** [comment]
Yes, at the moment extension versions are tied directly to DuckDB versions, and yes, if you upgrade to the latest DuckDB prerelease you'll be able to install the latest SQLite scanner prerelease
